#include <time.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
/**
 * Problem 44 on Project Euler
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
 *
 * Triangle     Tn=n(n+1)/2     1, 3, 6,        10, 15, ...
 * Pentagonal   Pn=n(3n−1)/2    1, 5, 12, 22, 35, ...
 * Hexagon      al  Hn=n(2n−1)  1, 6, 15, 28, 45, ...
 * It can be verified that T285         = P165 = H143 = 40755.
 *
 * Find the next triangle number that is also pentagonal and hexagonal.
 *
 * PLEASE NOTE
 * In order to compile this Algorithm you must have gcc, or similar, installed
 *
 * REGARDING THE PERFORMANCE
 * This is not the final version of the script, anyone can improve it.
 * If you have a better solution please submit a pull request, or an issue, on Github.
 *
 * @author Claudio Ludovico Panetta (@Ludo237)
 *
 * @version 1.0.0
 **/

int main(int argc, char *argv[])
{
    // Benchmark variables
    double start, end;
    // Helper variables
    unsigned long int counter = (285 + 1) / 2;
    unsigned long int square = 0, temp = 0, total = 0;
    // Start
    start = clock();
    printf("Algorithm starts, please wait...\n");
    do
    {
        counter ++;
        // Main formula
        temp = 48 * counter * counter - 24 * counter + 1;
        square = sqrt(temp);
    }
    while( (square + 1) % 6 != 0 || square * square != temp);
    total = counter * (2 * counter - 1);
    end = clock();
    printf("Algorithm end.\n");
    printf("Total time: %f\n", (end - start)/CLOCKS_PER_SEC);
    return 0;
}
